-- Schema PostgreSQL enxuto para o AutoVenda Pro B2B.
-- Regra principal: toda tabela de negocio carrega loja_id para isolamento por loja.
-- Pensado para poucas lojas e sem recursos avancados do PostgreSQL.

-- Lojas do SaaS.
CREATE TABLE IF NOT EXISTS lojas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  slug text NOT NULL UNIQUE,
  documento text,
  telefone text,
  email_contato text,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'suspended')),
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp
);

-- Usuarios globais do sistema.
CREATE TABLE IF NOT EXISTS usuarios (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome text NOT NULL,
  email text NOT NULL UNIQUE,
  senha_hash text NOT NULL,
  ativo boolean NOT NULL DEFAULT true,
  ultimo_login_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp
);

-- Vinculo do usuario com a loja e seu papel nela.
CREATE TABLE IF NOT EXISTS membros_loja (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  usuario_id bigint NOT NULL REFERENCES usuarios(id) ON DELETE CASCADE,
  papel text NOT NULL CHECK (papel IN ('owner', 'seller')),
  ativo boolean NOT NULL DEFAULT true,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (loja_id, usuario_id)
);
CREATE INDEX IF NOT EXISTS idx_membros_loja_usuario_id ON membros_loja (usuario_id);
CREATE INDEX IF NOT EXISTS idx_membros_loja_loja_papel ON membros_loja (loja_id, papel);

-- Convites para entrar na loja.
CREATE TABLE IF NOT EXISTS convites (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  email text NOT NULL,
  papel text NOT NULL CHECK (papel IN ('owner', 'seller')),
  token text NOT NULL UNIQUE,
  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'accepted', 'revoked', 'expired')),
  convidado_por_usuario_id bigint NOT NULL,
  aceito_por_usuario_id bigint,
  expira_em timestamptz NOT NULL,
  aceito_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  FOREIGN KEY (loja_id, convidado_por_usuario_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT,
  FOREIGN KEY (aceito_por_usuario_id) REFERENCES usuarios (id) ON DELETE SET NULL
);
CREATE INDEX IF NOT EXISTS idx_convites_loja_email ON convites (loja_id, email);
CREATE INDEX IF NOT EXISTS idx_convites_loja_status_expira ON convites (loja_id, status, expira_em);
CREATE INDEX IF NOT EXISTS idx_convites_convidado_por ON convites (convidado_por_usuario_id);

-- Sessoes autenticadas no contexto de uma loja.
CREATE TABLE IF NOT EXISTS sessoes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  usuario_id bigint NOT NULL,
  token_hash text NOT NULL UNIQUE,
  ip_address text,
  user_agent text,
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  last_seen_at timestamptz,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  FOREIGN KEY (loja_id, usuario_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_sessoes_usuario_loja ON sessoes (usuario_id, loja_id);
CREATE INDEX IF NOT EXISTS idx_sessoes_expires_at ON sessoes (expires_at);

-- Trial e licenca da loja.
CREATE TABLE IF NOT EXISTS assinaturas_loja (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL UNIQUE REFERENCES lojas(id) ON DELETE CASCADE,
  tipo text NOT NULL CHECK (tipo IN ('trial', 'licenca')),
  status text NOT NULL DEFAULT 'trial' CHECK (status IN ('trial', 'active', 'past_due', 'expired', 'canceled')),
  starts_at timestamptz NOT NULL DEFAULT current_timestamp,
  trial_ends_at timestamptz,
  ends_at timestamptz,
  license_key_hash text UNIQUE,
  seat_limit integer NOT NULL DEFAULT 10 CHECK (seat_limit > 0),
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  CHECK (tipo = 'trial' OR license_key_hash IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS idx_assinaturas_status ON assinaturas_loja (status);
CREATE INDEX IF NOT EXISTS idx_assinaturas_ends_at ON assinaturas_loja (ends_at);

-- Estoque de veiculos.
CREATE TABLE IF NOT EXISTS veiculos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  vendedor_id bigint,
  placa text,
  marca text,
  modelo text NOT NULL,
  ano text NOT NULL,
  km integer,
  cor text,
  cambio text,
  tem_multimidia boolean,
  opcionais text,
  custo numeric(12,2) NOT NULL DEFAULT 0 CHECK (custo >= 0),
  valor_venda numeric(12,2) NOT NULL DEFAULT 0 CHECK (valor_venda >= 0),
  valor_fipe numeric(12,2),
  status text NOT NULL DEFAULT 'disponivel' CHECK (status IN ('disponivel', 'reservado', 'vendido')),
  titulo_anuncio text,
  descricao_olx text,
  descricao_marketplace text,
  descricao_whatsapp text,
  fotos jsonb NOT NULL DEFAULT '[]'::jsonb,
  fotos_destaque jsonb NOT NULL DEFAULT '[]'::jsonb,
  ajustes_foto jsonb NOT NULL DEFAULT '{}'::jsonb,
  foto_capa_index integer NOT NULL DEFAULT 0 CHECK (foto_capa_index >= 0),
  vendido_em timestamptz,
  arquivado_em timestamptz,
  excluido_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (loja_id, id),
  UNIQUE (loja_id, placa),
  FOREIGN KEY (loja_id, vendedor_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_veiculos_loja_status ON veiculos (loja_id, status);
CREATE INDEX IF NOT EXISTS idx_veiculos_loja_vendedor ON veiculos (loja_id, vendedor_id);
CREATE INDEX IF NOT EXISTS idx_veiculos_loja_criado ON veiculos (loja_id, criado_em DESC);

-- Leads e funil comercial.
CREATE TABLE IF NOT EXISTS leads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  vendedor_id bigint NOT NULL,
  veiculo_id bigint,
  nome text NOT NULL,
  telefone text NOT NULL,
  interesse text NOT NULL,
  origem text NOT NULL CHECK (origem IN ('manual', 'marketplace', 'whatsapp', 'meta_ads')),
  status text NOT NULL DEFAULT 'novo' CHECK (status IN ('novo', 'em_contato', 'fechado', 'perdido')),
  historico jsonb NOT NULL DEFAULT '[]'::jsonb,
  anotacoes text NOT NULL DEFAULT '',
  arquivado_em timestamptz,
  excluido_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (loja_id, id),
  FOREIGN KEY (loja_id, vendedor_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, veiculo_id) REFERENCES veiculos (loja_id, id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_leads_loja_status ON leads (loja_id, status);
CREATE INDEX IF NOT EXISTS idx_leads_loja_vendedor ON leads (loja_id, vendedor_id);
CREATE INDEX IF NOT EXISTS idx_leads_loja_veiculo ON leads (loja_id, veiculo_id);
CREATE INDEX IF NOT EXISTS idx_leads_loja_criado ON leads (loja_id, criado_em DESC);

-- Consultas veiculares.
CREATE TABLE IF NOT EXISTS consultas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  usuario_id bigint NOT NULL,
  veiculo_id bigint,
  placa text NOT NULL,
  resultado jsonb NOT NULL DEFAULT '{}'::jsonb,
  consultado_em timestamptz NOT NULL DEFAULT current_timestamp,
  FOREIGN KEY (loja_id, usuario_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, veiculo_id) REFERENCES veiculos (loja_id, id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_consultas_loja_placa ON consultas (loja_id, placa);
CREATE INDEX IF NOT EXISTS idx_consultas_loja_veiculo ON consultas (loja_id, veiculo_id);
CREATE INDEX IF NOT EXISTS idx_consultas_loja_consultado ON consultas (loja_id, consultado_em DESC);

-- Vendas realizadas.
CREATE TABLE IF NOT EXISTS vendas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  veiculo_id bigint NOT NULL,
  lead_id bigint,
  vendedor_id bigint NOT NULL,
  valor numeric(12,2) NOT NULL CHECK (valor >= 0),
  data_venda date NOT NULL,
  observacoes text,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  UNIQUE (loja_id, id),
  UNIQUE (loja_id, veiculo_id),
  FOREIGN KEY (loja_id, veiculo_id) REFERENCES veiculos (loja_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, vendedor_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, lead_id) REFERENCES leads (loja_id, id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_vendas_loja_vendedor ON vendas (loja_id, vendedor_id);
CREATE INDEX IF NOT EXISTS idx_vendas_loja_data ON vendas (loja_id, data_venda DESC);

-- Custos vinculados a veiculos.
CREATE TABLE IF NOT EXISTS custos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  veiculo_id bigint NOT NULL,
  categoria text NOT NULL CHECK (categoria IN ('pintura', 'pneus', 'retrovisor', 'higienizacao', 'polimento', 'mecanica', 'outro')),
  descricao text NOT NULL,
  valor numeric(12,2) NOT NULL CHECK (valor >= 0),
  ocorrido_em date NOT NULL,
  criado_por_usuario_id bigint NOT NULL,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  FOREIGN KEY (loja_id, veiculo_id) REFERENCES veiculos (loja_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, criado_por_usuario_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_custos_loja_veiculo ON custos (loja_id, veiculo_id);
CREATE INDEX IF NOT EXISTS idx_custos_loja_categoria ON custos (loja_id, categoria);
CREATE INDEX IF NOT EXISTS idx_custos_loja_ocorrido ON custos (loja_id, ocorrido_em DESC);

-- Tarefas de pos-venda.
CREATE TABLE IF NOT EXISTS tarefas (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  loja_id bigint NOT NULL REFERENCES lojas(id) ON DELETE CASCADE,
  venda_id bigint NOT NULL,
  veiculo_id bigint NOT NULL,
  titulo text NOT NULL,
  descricao text,
  categoria text NOT NULL CHECK (categoria IN ('documento', 'reparo', 'limpeza', 'multa', 'entrega', 'outro')),
  status text NOT NULL DEFAULT 'pendente' CHECK (status IN ('pendente', 'em_andamento', 'concluida')),
  responsavel_usuario_id bigint,
  concluido_em timestamptz,
  criado_em timestamptz NOT NULL DEFAULT current_timestamp,
  atualizado_em timestamptz NOT NULL DEFAULT current_timestamp,
  FOREIGN KEY (loja_id, venda_id) REFERENCES vendas (loja_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, veiculo_id) REFERENCES veiculos (loja_id, id) ON DELETE RESTRICT,
  FOREIGN KEY (loja_id, responsavel_usuario_id) REFERENCES membros_loja (loja_id, usuario_id) ON DELETE RESTRICT
);
CREATE INDEX IF NOT EXISTS idx_tarefas_loja_venda ON tarefas (loja_id, venda_id);
CREATE INDEX IF NOT EXISTS idx_tarefas_loja_veiculo ON tarefas (loja_id, veiculo_id);
CREATE INDEX IF NOT EXISTS idx_tarefas_loja_status ON tarefas (loja_id, status);

-- Dica operacional: o app deve filtrar sempre por loja_id e atualizar os campos atualizado_em.
